### ISSUE TITLE
Environment-specific override of common settings

### ISSUE THREAD

**Issue by warnergodfrey** [bernos/eb-deployer-js#23]
The original eb_deployer allows environment-specific overrides to common config.

See the `example for overriding common settings` section in the default yml config:
https://github.com/ThoughtWorksStudios/eb_deployer/wiki/Default-Configuration

An example where the environment-specific override would be useful is to override the bucket where the package is deployed.

I've spiked a change to https://github.com/bernos/eb-deployer-js/blob/master/src/strategies/blue-green/states/validating-configuration.js and successfully overrode the bucket config. I'll get this working for other common settings and submit a PR.

**Comment by bernos** [comment]
Closed in v1.1.0
