### ISSUE TITLE
Bucket names need to be unique.

### ISSUE THREAD

**Issue by jamesdavidson** [bernos/eb-deployer-js#4]
Hi there, I tried to run your example but creating the S3 bucket for the packages failed because [my-application-packages.s3-ap-southeast-2.amazonaws.com](http://my-application-packages.s3-ap-southeast-2.amazonaws.com) is already taken. Perhaps consider prefixing the bucket names with the account's numerical identifier?

**Comment by jamesdavidson** [comment]
Also you should tweak the regex in normalizeApplicationName. Make it `/\s/g` instead of just `/\s/` so that it's more robust.

**Comment by bernos** [comment]
Good idea, thanks James

**Comment by bernos** [comment]
Am going to allow the name of the bucket to be explicitly set in config. Retrieving the aws account id via API is surprisingly not so straight forward. The current autogenererated bucket name will still be used as a fallback if nothing is specified in the config
